import { useState } from "react";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { createSchoolClass } from "../../services/school-admin/school-admin.service";

export default function ClassCreateScreen(){
 const [name,setName]=useState(""); const [level,setLevel]=useState(""); const [saving,setSaving]=useState(false);
 const submit=async()=>{if(!name.trim()||!level.trim()){Alert.alert("Champs requis","Le nom et le niveau sont obligatoires.");return;}try{setSaving(true);await createSchoolClass({name:name.trim(),level:level.trim()});Alert.alert("Classe créée","La classe a été ajoutée à l'année scolaire active.",[{text:"OK",onPress:()=>router.replace("/(app)/classes")}]);}catch(error:any){Alert.alert("Création impossible",error?.response?.data?.error?.message??"Une erreur est survenue.");}finally{setSaving(false);}};
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.title}>Nouvelle classe</Text><Text style={styles.subtitle}>Elle sera ajoutée à l'année scolaire active.</Text><Text style={styles.label}>Nom de la classe</Text><TextInput value={name} onChangeText={setName} placeholder="Ex. CM2 A" style={styles.input}/><Text style={styles.label}>Niveau / cycle</Text><TextInput value={level} onChangeText={setLevel} placeholder="Ex. Primaire" style={styles.input}/><Pressable disabled={saving} onPress={()=>void submit()} style={styles.button}><Text style={styles.buttonText}>{saving?"Création…":"Créer la classe"}</Text></Pressable><Pressable onPress={()=>router.back()} style={styles.cancel}><Text>Annuler</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F8FAFC"},content:{padding:20},title:{fontSize:25,fontWeight:"800",color:"#344976"},subtitle:{marginTop:5,marginBottom:24,color:"#6B7280"},label:{marginTop:14,marginBottom:7,fontWeight:"700",color:"#374151"},input:{height:48,borderWidth:1,borderColor:"#D9DEE5",borderRadius:12,paddingHorizontal:13,backgroundColor:"#FFF"},button:{marginTop:24,padding:15,borderRadius:12,backgroundColor:"#344976",alignItems:"center"},buttonText:{color:"#FFF",fontWeight:"800"},cancel:{marginTop:14,padding:14,alignItems:"center"}});
