import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { getSecretariatTickets, createSecretariatTicket, updateSecretariatTicket } from "../../services/secretariat/secretariat.service";
import type { SecretariatTicket } from "../../services/secretariat/secretariat.types";
import { hasPermission } from "../../features/secretariat/access";
import { useAuthStore } from "../../stores/authStore";

const priorities: SecretariatTicket["priority"][]=["LOW","NORMAL","HIGH","URGENT"];
const statuses: SecretariatTicket["status"][]=["OPEN","IN_PROGRESS","RESOLVED","CLOSED"];

export default function SecretariatTicketsScreen(){
  const router=useRouter(); const user=useAuthStore(s=>s.user);
  const [items,setItems]=useState<SecretariatTicket[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
  const [subject,setSubject]=useState(""); const [description,setDescription]=useState(""); const [priority,setPriority]=useState<SecretariatTicket["priority"]>("NORMAL");
  const load=useCallback(async()=>{try{setItems((await getSecretariatTickets()).tickets);}catch{Alert.alert("Erreur","Impossible de charger les demandes internes.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const create=async()=>{if(!subject.trim()||!description.trim()){Alert.alert("Champs requis","Objet et description sont obligatoires.");return;}try{setSaving(true);const r=await createSecretariatTicket({subject:subject.trim(),description:description.trim(),priority});setItems(c=>[r.ticket,...c]);setSubject("");setDescription("");setPriority("NORMAL");setOpen(false);}catch(error:any){Alert.alert("Erreur",error?.response?.data?.error?.message??"Création impossible.");}finally{setSaving(false);}};
  const update=async(ticketId:string,input:Parameters<typeof updateSecretariatTicket>[1])=>{try{const r=await updateSecretariatTicket(ticketId,input);setItems(c=>c.map(x=>x.id===ticketId?r.ticket:x));}catch(error:any){Alert.alert("Erreur",error?.response?.data?.error?.message??"Mise à jour impossible.");}};
  if(!hasPermission(user,"ticket.read"))return <AccessDenied onBack={()=>router.back()}/>;
  if(loading)return <View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Chargement…</Text></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <Header title="Demandes internes" onBack={()=>router.back()}/>
    {hasPermission(user,"ticket.create")?<Pressable style={styles.primary} onPress={()=>setOpen(v=>!v)}><Text style={styles.primaryText}>{open?"Fermer":"+ Nouvelle demande"}</Text></Pressable>:null}
    {open?<View style={styles.form}><TextInput value={subject} onChangeText={setSubject} placeholder="Objet" style={styles.input}/><TextInput value={description} onChangeText={setDescription} placeholder="Description" multiline style={[styles.input,styles.multi]}/><Text style={styles.label}>Priorité</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{priorities.map(p=><Pressable key={p} style={[styles.chip,p===priority&&styles.active]} onPress={()=>setPriority(p)}><Text style={styles.chipText}>{p}</Text></Pressable>)}</ScrollView><Pressable disabled={saving} style={styles.primary} onPress={()=>void create()}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Créer</Text>}</Pressable></View>:null}
    {items.length===0?<View style={styles.card}><Text style={styles.muted}>Aucune demande interne.</Text></View>:items.map(item=><View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.subject}</Text><Text style={styles.body}>{item.description}</Text><Text style={styles.muted}>Priorité : {item.priority}</Text>{hasPermission(user,"ticket.update")?<><Text style={styles.label}>Statut</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{statuses.map(s=><Pressable key={s} style={[styles.chip,s===item.status&&styles.active]} onPress={()=>void update(item.id,{status:s})}><Text style={styles.chipText}>{s}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Priorité</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{priorities.map(p=><Pressable key={p} style={[styles.chip,p===item.priority&&styles.active]} onPress={()=>void update(item.id,{priority:p})}><Text style={styles.chipText}>{p}</Text></Pressable>)}</ScrollView></>:null}</View>)}
  </ScrollView>;
}
function Header({title,onBack}:{title:string;onBack:()=>void}){return <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>{title}</Text></View>;}
function AccessDenied({onBack}:{onBack:()=>void}){return <View style={styles.center}><Text style={styles.cardTitle}>Accès non autorisé</Text><Pressable onPress={onBack} style={styles.primary}><Text style={styles.primaryText}>Retour</Text></Pressable></View>;}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F8FAFC"},content:{padding:16,paddingBottom:36,gap:12},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24,gap:10},header:{flexDirection:"row",alignItems:"center",gap:12},back:{fontSize:34,color:"#111827"},title:{fontSize:24,fontWeight:"800",color:"#111827"},primary:{minHeight:44,paddingHorizontal:15,borderRadius:11,backgroundColor:"#111827",alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"800"},form:{padding:14,borderRadius:14,backgroundColor:"#fff",borderWidth:1,borderColor:"#E5E7EB",gap:9},input:{minHeight:44,borderWidth:1,borderColor:"#D1D5DB",borderRadius:10,paddingHorizontal:12,color:"#111827",backgroundColor:"#fff"},multi:{minHeight:90,paddingTop:12,textAlignVertical:"top"},label:{fontSize:12,fontWeight:"800",color:"#374151"},chips:{gap:7},chip:{paddingHorizontal:11,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:"#D1D5DB",backgroundColor:"#fff"},active:{backgroundColor:"#EEF2F7",borderColor:"#344976"},chipText:{fontSize:11,fontWeight:"700",color:"#374151"},card:{padding:15,borderRadius:14,backgroundColor:"#fff",borderWidth:1,borderColor:"#E5E7EB",gap:7},cardTitle:{fontSize:16,fontWeight:"800",color:"#111827"},body:{fontSize:13,lineHeight:19,color:"#374151"},muted:{fontSize:12,color:"#6B7280"}});
