-- Historical migration retained for migration-history compatibility.
-- The index is created by the later response-read migration.
-- This migration is intentionally a no-op so the full history replays cleanly.
